In [1]:
#Packages
import h5py
import os
import numpy as np    
import matplotlib.pyplot as plt
from scipy.constants import pi
from scipy.optimize import curve_fit as fit
import func as func

### Plotting 3D:

In [ ]:
#Directory with data:
datadir = "G2-lcdm-gas/"

files = os.listdir(datadir+".")
files.sort()
for file in files:    #Importing data (Particle Type 1 - dark matter, Particle Type 2 - baryonic matter):
    f = h5py.File(datadir+file, "r")
    group = f["PartType0"]
    data = group["Coordinates"][()]
    dens = group["Density"][()]
    
    #Plotting the initial conditions of both galaxies:
    fig = plt.figure(dpi=200)
    ax = plt.axes(projection='3d')
    plot = ax.scatter3D(data[:,0],data[:,1],data[:,2],'k.',s=0.5,c=dens,cmap="jet",alpha=0.1)
    cbar = fig.colorbar(plot, ax = ax)
    cbar.set_label('Density', rotation=0)
    plt.show()

### Distances to one particle:

In [62]:
datadir = "G2-lcdm-gas/"
files = os.listdir(datadir+".")
files.sort()

f = h5py.File(datadir+"snapshot_000.hdf5", "r")
group = f["PartType0"]
data = group["Coordinates"][()]
dmax=np.sqrt(3)*50000

hist=[]
np.array(hist)
for j in range(1,100):
    d=[]
    for i in range(1,len(data)):
        r=np.sqrt((abs(data[j,0]-data[i,0])**2) + (abs(data[j,1]-data[i,1])**2) + (abs(data[j,2]-data[i,2])**2))
        d=np.append(d,r)
    n,bins=np.histogram(d,bins=100,range=(0,dmax))
    n.astype(float)
    hist=np.append(hist,n)

In [17]:
n,c=np.histogram(d,bins=100)
n.astype(float)

array([  5.,   3.,   6.,   9.,   7.,  12.,  11.,  12.,  16.,  24.,  31.,
        32.,  47.,  46.,  55.,  62.,  74.,  92., 105., 117., 123., 123.,
       132., 144., 157., 178., 193., 210., 236., 249., 277., 294., 313.,
       311., 343., 389., 369., 396., 426., 452., 465., 467., 497., 469.,
       507., 503., 522., 560., 574., 602., 596., 624., 657., 647., 711.,
       763., 778., 898., 816., 855., 823., 812., 762., 777., 738., 724.,
       696., 678., 700., 646., 633., 602., 556., 533., 492., 478., 420.,
       385., 389., 345., 324., 278., 256., 213., 164., 144., 122.,  91.,
        87.,  76.,  48.,  41.,  40.,  31.,  21.,  16.,  14.,  11.,   5.,
         4.])

In [54]:
len(hist[0])

9900

In [53]:
n

array([  1,   3,   7,  11,  18,  30,  46,  51,  81,  93, 105, 115, 145,
       145, 171, 177, 184, 200, 208, 236, 246, 278, 337, 371, 381, 403,
       449, 431, 440, 453, 483, 470, 510, 500, 546, 532, 548, 561, 621,
       625, 649, 690, 752, 753, 785, 810, 839, 918, 913, 870, 861, 824,
       840, 821, 840, 843, 768, 736, 697, 656, 627, 589, 551, 497, 472,
       425, 389, 333, 301, 292, 252, 211, 171, 127,  96,  81,  73,  51,
        41,  31,  28,  19,  15,  10,   6,   2,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0])

In [61]:
hist=[[],[]]
np.array(hist)
np.shape(hist)

(2, 0)

In [63]:
hist

array([1., 1., 6., ..., 0., 0., 0.])